### ISSUE TITLE
Flask項目部署的問題

### ISSUE THREAD

**Issue by jack-fox-gif** [0Kee-Team/WatchAD-Web#3]
您好，小白一個，請教下uwsgi.ini中的{your_project_dir}，指的是'WatchAD-Web-master/server'這個目錄麼，nginx.conf中的{your_project_dir}是一樣的麼；
另外nginx.conf中的‘’include /etc/nginx/default.d/*.conf‘’，默認沒有這個文件，能否提供下配置。
在frontend中npm run build之後的dist文件夾是如何處理，感謝指教！

**Comment by Qianlitp** [comment]
已经更新了Docker一键化部署，请参考README安装部署。

**Comment by jack-fox-gif** [comment]
非常感謝
