### ISSUE TITLE
查询数据出错

### ISSUE THREAD

**Issue by PoolHell** [0Kee-Team/WatchAD-Web#4]
您好，我在ubuntu上运行了watchad和watchad-web，用网页打开显示查询数据出错，找不到是哪里配置不对，还请指点。
![image](https://user-images.githubusercontent.com/18211519/71146187-308ce900-225f-11ea-99fd-a601e12a3cb2.png)

**Comment by Qianlitp** [comment]
1. 首先，确认后端服务配置正确：https://github.com/0Kee-Team/WatchAD-Web/blob/master/server/config/database_config.py
2. 确认Vue项目正确指向后端服务 https://github.com/0Kee-Team/WatchAD-Web/blob/deb00d5eba4f5726752a0b6d539e7c04f480a6f0/frontend/.env.production#L1

报错的话，在console里能看到具体错误，烦请贴出。
如果是后端502错误，可以查看server 容器的日志输出

**Comment by PoolHell** [comment]
ip的配置没有问题，和你的一样，要不微信聊吧，我的微信号是HelloFeng_0511。
![image](https://user-images.githubusercontent.com/18211519/71152476-7d79bb00-2271-11ea-9a57-66bcf04337fe.png)

**Comment by PoolHell** [comment]
你好，我看容器的日志，有下面这种情况
![image](https://user-images.githubusercontent.com/18211519/71333971-2f1d3280-2577-11ea-80d7-04241f207211.png)
![image](https://user-images.githubusercontent.com/18211519/71333993-42c89900-2577-11ea-8729-7206fbb496d4.png)
是这两个数据库问题造成的吗？

**Comment by Junm0** [comment]
解决了嘛，我也遇到同样的问题

**Comment by Qianlitp** [comment]
配置文件 https://github.com/0Kee-Team/WatchAD-Web/blob/master/server/config/database_config.py 修改其中的Host地址，因为是在docker环境，不要填写127.0.0.1，改为本机实际IP地址。

**Comment by PoolHell** [comment]
> 解决了嘛，我也遇到同样的问题

没有解决，将127.0.0.1改为本地实际地址也还是那个错误，准备换个机器试试

**Comment by Qianlitp** [comment]
> > 解决了嘛，我也遇到同样的问题
> 
> 没有解决，将127.0.0.1改为本地实际地址也还是那个错误，准备换个机器试试

前端报错，看前端日志，404还是500 502，如果是500或者502，查看后端报错输出 docker logs `容器ID`。
